# Generated by Django 5.1.2 on 2024-11-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adltest',
            name='valor1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
