# Generated by Django 5.1.2 on 2024-12-04 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_tarea_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('eliminada', models.BooleanField(default=False)),
                ('tarea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.tarea')),
            ],
        ),
    ]
